version: '3.3'

networks:
  api:

services:
  api-service:
    container_name: api-service
    build: ./deployment
    volumes:
    - ./deployment:/deployment
    - ./code:/var/www/symfony
    working_dir: /var/www/symfony
    depends_on:
    - db-service
    networks:
    - api
    ports:
    - 80:80
    command: sh /deployment/start.sh


  db-service:
    image: mysql:5.7
    container_name: db-service
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=cart_api
    - MYSQL_USER=cart_api
    - MYSQL_PASSWORD=cart_api
    - MYSQL_DATABASE=cart_api
    networks:
    - api

